[package]
name = "dcpd"
description = "Desktop Context Protocol — core daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "dcpd"
path = "src/main.rs"

[dependencies]
dcp-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio-util = { workspace = true }
bytes = { workspace = true }
uuid = { workspace = true }
base64 = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
async-trait = "0.1"
tracing-subscriber = "0.3"
tokio = { workspace = true, features = ["full", "process"] }
zbus = "4"
notify = "6"
wayland-client = "0.31"
wayland-protocols = { version = "0.31", features = ["client"] }
tokio-tungstenite = { version = "0.21", features = ["rustls"] }
tokio-rustls = "0.25"
rustls = "0.22"
rustls-pemfile = "2"
toml = "0.8"
dirs = "5"
tesseract = "0.15"
image = "0.25"
